// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginType categorizes what kind of component a plugin represents.
type PluginType int32

const (
	PluginType_PLUGIN_TYPE_UNSPECIFIED   PluginType = 0
	PluginType_PLUGIN_TYPE_QUERY_ENGINE  PluginType = 1  // Trino, Dremio — receives SQL, returns results
	PluginType_PLUGIN_TYPE_PROCESSING    PluginType = 2  // Spark, Flink, DataFusion — creates pods/CRDs
	PluginType_PLUGIN_TYPE_ORCHESTRATION PluginType = 3  // Airflow — observability bridge + trigger
	PluginType_PLUGIN_TYPE_STORAGE       PluginType = 4  // Ceph, MinIO
	PluginType_PLUGIN_TYPE_CATALOG       PluginType = 5  // Polaris, Nessie, Hive
	PluginType_PLUGIN_TYPE_STREAMING     PluginType = 6  // Kafka, AutoMQ, Redpanda
	PluginType_PLUGIN_TYPE_ML            PluginType = 7  // MLflow, Ray
	PluginType_PLUGIN_TYPE_OBSERVABILITY PluginType = 8  // Prometheus, Grafana
	PluginType_PLUGIN_TYPE_NOTEBOOK      PluginType = 9  // JupyterHub, Marimo
	PluginType_PLUGIN_TYPE_BI            PluginType = 10 // Superset, Metabase
	PluginType_PLUGIN_TYPE_GENERIC       PluginType = 99 // anything else
)

// Enum value maps for PluginType.
var (
	PluginType_name = map[int32]string{
		0:  "PLUGIN_TYPE_UNSPECIFIED",
		1:  "PLUGIN_TYPE_QUERY_ENGINE",
		2:  "PLUGIN_TYPE_PROCESSING",
		3:  "PLUGIN_TYPE_ORCHESTRATION",
		4:  "PLUGIN_TYPE_STORAGE",
		5:  "PLUGIN_TYPE_CATALOG",
		6:  "PLUGIN_TYPE_STREAMING",
		7:  "PLUGIN_TYPE_ML",
		8:  "PLUGIN_TYPE_OBSERVABILITY",
		9:  "PLUGIN_TYPE_NOTEBOOK",
		10: "PLUGIN_TYPE_BI",
		99: "PLUGIN_TYPE_GENERIC",
	}
	PluginType_value = map[string]int32{
		"PLUGIN_TYPE_UNSPECIFIED":   0,
		"PLUGIN_TYPE_QUERY_ENGINE":  1,
		"PLUGIN_TYPE_PROCESSING":    2,
		"PLUGIN_TYPE_ORCHESTRATION": 3,
		"PLUGIN_TYPE_STORAGE":       4,
		"PLUGIN_TYPE_CATALOG":       5,
		"PLUGIN_TYPE_STREAMING":     6,
		"PLUGIN_TYPE_ML":            7,
		"PLUGIN_TYPE_OBSERVABILITY": 8,
		"PLUGIN_TYPE_NOTEBOOK":      9,
		"PLUGIN_TYPE_BI":            10,
		"PLUGIN_TYPE_GENERIC":       99,
	}
)

func (x PluginType) Enum() *PluginType {
	p := new(PluginType)
	*p = x
	return p
}

func (x PluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginType) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[0]
}

func (x PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginType.Descriptor instead.
func (PluginType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

// ExecutionType distinguishes how a plugin executes work.
type ExecutionType int32

const (
	ExecutionType_EXECUTION_TYPE_UNSPECIFIED ExecutionType = 0
	// WORKLOAD: creates pods/CRDs in the cluster to process data.
	// Examples: Spark, Flink, User Pod, DataFusion/Ballista.
	// Has: submit, kill, logs, metrics, status tied to pod lifecycle.
	ExecutionType_EXECUTION_TYPE_WORKLOAD ExecutionType = 1
	// QUERY: sends work to a running service that processes it internally.
	// Examples: Trino, Dremio.
	// Has: submit query, cancel, results, query stats.
	// Does NOT create pods.
	ExecutionType_EXECUTION_TYPE_QUERY ExecutionType = 2
	// OBSERVABILITY: reads state from external systems, does not execute work.
	// Examples: Airflow (reads DAG runs), OpenMetadata.
	ExecutionType_EXECUTION_TYPE_OBSERVABILITY ExecutionType = 3
)

// Enum value maps for ExecutionType.
var (
	ExecutionType_name = map[int32]string{
		0: "EXECUTION_TYPE_UNSPECIFIED",
		1: "EXECUTION_TYPE_WORKLOAD",
		2: "EXECUTION_TYPE_QUERY",
		3: "EXECUTION_TYPE_OBSERVABILITY",
	}
	ExecutionType_value = map[string]int32{
		"EXECUTION_TYPE_UNSPECIFIED":   0,
		"EXECUTION_TYPE_WORKLOAD":      1,
		"EXECUTION_TYPE_QUERY":         2,
		"EXECUTION_TYPE_OBSERVABILITY": 3,
	}
)

func (x ExecutionType) Enum() *ExecutionType {
	p := new(ExecutionType)
	*p = x
	return p
}

func (x ExecutionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (ExecutionType) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[1]
}

func (x ExecutionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionType.Descriptor instead.
func (ExecutionType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

// WorkloadType applies only to EXECUTION_TYPE_WORKLOAD.
type WorkloadType int32

const (
	WorkloadType_WORKLOAD_TYPE_UNSPECIFIED WorkloadType = 0
	// BATCH: job runs, completes, and terminates.
	// Examples: Spark batch job, Flink batch job, Python script.
	WorkloadType_WORKLOAD_TYPE_BATCH WorkloadType = 1
	// STREAMING: job runs indefinitely, processes continuous data.
	// Examples: Spark Structured Streaming, Flink CDC, Go Protobuf consumer.
	// Has additional capabilities: savepoint, restore, consumer lag metrics.
	WorkloadType_WORKLOAD_TYPE_STREAMING WorkloadType = 2
)

// Enum value maps for WorkloadType.
var (
	WorkloadType_name = map[int32]string{
		0: "WORKLOAD_TYPE_UNSPECIFIED",
		1: "WORKLOAD_TYPE_BATCH",
		2: "WORKLOAD_TYPE_STREAMING",
	}
	WorkloadType_value = map[string]int32{
		"WORKLOAD_TYPE_UNSPECIFIED": 0,
		"WORKLOAD_TYPE_BATCH":       1,
		"WORKLOAD_TYPE_STREAMING":   2,
	}
)

func (x WorkloadType) Enum() *WorkloadType {
	p := new(WorkloadType)
	*p = x
	return p
}

func (x WorkloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[2].Descriptor()
}

func (WorkloadType) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[2]
}

func (x WorkloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadType.Descriptor instead.
func (WorkloadType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

// HealthState represents the current health of a component.
type HealthState int32

const (
	HealthState_HEALTH_STATE_UNSPECIFIED HealthState = 0
	HealthState_HEALTH_STATE_HEALTHY     HealthState = 1
	HealthState_HEALTH_STATE_DEGRADED    HealthState = 2
	HealthState_HEALTH_STATE_UNHEALTHY   HealthState = 3
	HealthState_HEALTH_STATE_UNKNOWN     HealthState = 4
)

// Enum value maps for HealthState.
var (
	HealthState_name = map[int32]string{
		0: "HEALTH_STATE_UNSPECIFIED",
		1: "HEALTH_STATE_HEALTHY",
		2: "HEALTH_STATE_DEGRADED",
		3: "HEALTH_STATE_UNHEALTHY",
		4: "HEALTH_STATE_UNKNOWN",
	}
	HealthState_value = map[string]int32{
		"HEALTH_STATE_UNSPECIFIED": 0,
		"HEALTH_STATE_HEALTHY":     1,
		"HEALTH_STATE_DEGRADED":    2,
		"HEALTH_STATE_UNHEALTHY":   3,
		"HEALTH_STATE_UNKNOWN":     4,
	}
)

func (x HealthState) Enum() *HealthState {
	p := new(HealthState)
	*p = x
	return p
}

func (x HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[3].Descriptor()
}

func (HealthState) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[3]
}

func (x HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthState.Descriptor instead.
func (HealthState) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

// JobState represents the lifecycle state of a submitted job or query.
type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_STATE_PENDING     JobState = 1
	JobState_JOB_STATE_RUNNING     JobState = 2
	JobState_JOB_STATE_SUCCEEDED   JobState = 3
	JobState_JOB_STATE_FAILED      JobState = 4
	JobState_JOB_STATE_CANCELED    JobState = 5
	JobState_JOB_STATE_UNKNOWN     JobState = 6
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_PENDING",
		2: "JOB_STATE_RUNNING",
		3: "JOB_STATE_SUCCEEDED",
		4: "JOB_STATE_FAILED",
		5: "JOB_STATE_CANCELED",
		6: "JOB_STATE_UNKNOWN",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_PENDING":     1,
		"JOB_STATE_RUNNING":     2,
		"JOB_STATE_SUCCEEDED":   3,
		"JOB_STATE_FAILED":      4,
		"JOB_STATE_CANCELED":    5,
		"JOB_STATE_UNKNOWN":     6,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[4].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[4]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

// Component holds the runtime configuration of a registered component.
// Passed to every RPC so the plugin knows what it is operating on.
type Component struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique name of this component instance.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Kubernetes namespace where this component lives.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Base URL to reach the component.
	// For query engines: the HTTP endpoint (e.g. http://trino:8080).
	// For K8s-native plugins (Spark, Flink): the K8s API server URL or empty.
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Arbitrary plugin-specific configuration key-value pairs.
	// Examples:
	//
	//	Spark:   { "namespace": "spark-operator-v2", "service_account": "spark" }
	//	Flink:   { "namespace": "da-flink", "workload_type": "streaming" }
	//	Trino:   { "catalog": "iceberg", "default_schema": "bronze" }
	//	UserPod: { "namespace": "cosmonaut-jobs", "mode": "deployment" }
	Config        map[string]string `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Component) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Component) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Component) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Component) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// Capability describes a single action a plugin supports.
type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // e.g. "query", "submit-job", "savepoint"
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Capability) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Capability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

type DescribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique plugin identifier. Must be lowercase, hyphen-separated.
	// Examples: "trino", "spark", "flink", "dremio", "userpod"
	PluginName string `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	// Human-readable name shown in the UI.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Plugin version (semver).
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Short description of what this plugin integrates.
	Description   string        `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PluginType    PluginType    `protobuf:"varint,5,opt,name=plugin_type,json=pluginType,proto3,enum=plugin.v1.PluginType" json:"plugin_type,omitempty"`
	ExecutionType ExecutionType `protobuf:"varint,6,opt,name=execution_type,json=executionType,proto3,enum=plugin.v1.ExecutionType" json:"execution_type,omitempty"`
	// workload_type is set only when execution_type = WORKLOAD.
	WorkloadType WorkloadType `protobuf:"varint,7,opt,name=workload_type,json=workloadType,proto3,enum=plugin.v1.WorkloadType" json:"workload_type,omitempty"`
	// Capabilities this plugin exposes.
	Capabilities  []*Capability `protobuf:"bytes,8,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *DescribeResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DescribeResponse) GetPluginType() PluginType {
	if x != nil {
		return x.PluginType
	}
	return PluginType_PLUGIN_TYPE_UNSPECIFIED
}

func (x *DescribeResponse) GetExecutionType() ExecutionType {
	if x != nil {
		return x.ExecutionType
	}
	return ExecutionType_EXECUTION_TYPE_UNSPECIFIED
}

func (x *DescribeResponse) GetWorkloadType() WorkloadType {
	if x != nil {
		return x.WorkloadType
	}
	return WorkloadType_WORKLOAD_TYPE_UNSPECIFIED
}

func (x *DescribeResponse) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     *Component             `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckRequest) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

type HealthCheckResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	State   HealthState            `protobuf:"varint,1,opt,name=state,proto3,enum=plugin.v1.HealthState" json:"state,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Optional structured details (e.g. version, active connections).
	Details       map[string]string `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetState() HealthState {
	if x != nil {
		return x.State
	}
	return HealthState_HEALTH_STATE_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type ExecuteRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Component *Component             `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	// Action to perform. Must match one of the plugin's declared capabilities.
	// Examples: "query", "submit-job", "savepoint", "trigger-dag", "run"
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// Action-specific payload.
	// Examples:
	//
	//	query:      { "sql": "SELECT ...", "catalog": "iceberg" }
	//	submit-job: { "image": "...", "main_class": "...", "args": "..." }
	//	savepoint:  { "job_id": "...", "target_path": "s3://..." }
	Payload       map[string]string `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteRequest) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *ExecuteRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecuteRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque ID assigned by the plugin to this execution.
	// For queries: the engine's internal query ID.
	// For workloads: the CRD name or K8s Job name.
	JobId string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State JobState `protobuf:"varint,2,opt,name=state,proto3,enum=plugin.v1.JobState" json:"state,omitempty"`
	// Human-readable message (error details, submission info, etc).
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Optional structured result data.
	// For queries: may include initial rows or query stats.
	// For workloads: may include the created CRD name/namespace.
	Result        map[string]string `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ExecuteResponse) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteResponse) GetResult() map[string]string {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     *Component             `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *GetJobRequest) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	JobId   string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State   JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=plugin.v1.JobState" json:"state,omitempty"`
	Message string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Structured status details.
	// For workloads: pod phase, restart count, node name.
	// For queries: rows scanned, bytes processed, wall time ms.
	Details       map[string]string `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *GetJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobResponse) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *GetJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetJobResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type ListJobsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Component *Component             `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	// Optional filter by state.
	StateFilter   JobState `protobuf:"varint,2,opt,name=state_filter,json=stateFilter,proto3,enum=plugin.v1.JobState" json:"state_filter,omitempty"`
	Limit         int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ListJobsRequest) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *ListJobsRequest) GetStateFilter() JobState {
	if x != nil {
		return x.StateFilter
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*GetJobResponse      `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ListJobsResponse) GetJobs() []*GetJobResponse {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     *Component             `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *CancelJobRequest) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Canceled      bool                   `protobuf:"varint,1,opt,name=canceled,proto3" json:"canceled,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *CancelJobResponse) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

func (x *CancelJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLogsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Component *Component             `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	JobId     string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// For workloads with multiple pods (driver + executors), which pod to fetch.
	// If empty, returns driver/primary logs.
	PodName string `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// Maximum number of log lines to return. 0 = no limit.
	TailLines     int32 `protobuf:"varint,4,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *GetLogsRequest) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *GetLogsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetLogsRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *GetLogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *GetLogsResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

type SavepointRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Component *Component             `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	JobId     string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Target path for the savepoint (e.g. s3://bucket/savepoints/).
	TargetPath string `protobuf:"bytes,3,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	// If true, cancel the job after the savepoint completes.
	CancelJob     bool `protobuf:"varint,4,opt,name=cancel_job,json=cancelJob,proto3" json:"cancel_job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavepointRequest) Reset() {
	*x = SavepointRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavepointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavepointRequest) ProtoMessage() {}

func (x *SavepointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavepointRequest.ProtoReflect.Descriptor instead.
func (*SavepointRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *SavepointRequest) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *SavepointRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SavepointRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *SavepointRequest) GetCancelJob() bool {
	if x != nil {
		return x.CancelJob
	}
	return false
}

type SavepointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SavepointPath string                 `protobuf:"bytes,1,opt,name=savepoint_path,json=savepointPath,proto3" json:"savepoint_path,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavepointResponse) Reset() {
	*x = SavepointResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavepointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavepointResponse) ProtoMessage() {}

func (x *SavepointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavepointResponse.ProtoReflect.Descriptor instead.
func (*SavepointResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *SavepointResponse) GetSavepointPath() string {
	if x != nil {
		return x.SavepointPath
	}
	return ""
}

func (x *SavepointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestoreRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Component *Component             `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	// Full savepoint path to restore from.
	SavepointPath string `protobuf:"bytes,2,opt,name=savepoint_path,json=savepointPath,proto3" json:"savepoint_path,omitempty"`
	// Original job payload to resubmit (same as ExecuteRequest.payload).
	Payload       map[string]string `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *RestoreRequest) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *RestoreRequest) GetSavepointPath() string {
	if x != nil {
		return x.SavepointPath
	}
	return ""
}

func (x *RestoreRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=plugin.v1.JobState" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *RestoreResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RestoreResponse) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *RestoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     *Component             `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *GetMetricsRequest) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *GetMetricsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetMetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key-value metrics reported by the plugin.
	// Examples (Flink): { "records_lag_max": "0", "checkpoint_duration_ms": "120" }
	// Examples (Spark):  { "input_rows": "1000000", "output_rows": "999000" }
	Metrics       map[string]string `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *GetMetricsResponse) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// HelmChart describes a Helm chart that can be installed by the Cosmonaut wizard.
type HelmChart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repo_url is the Helm repository URL.
	// Example: https://trinodb.github.io/charts
	RepoUrl string `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	// repo_name is the local alias for the Helm repo.
	// Example: trino
	RepoName string `protobuf:"bytes,2,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	// chart_name is the chart identifier within the repo.
	// Example: trino/trino
	ChartName string `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	// version is the chart version to install.
	// Example: 0.13.0
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// values_template is a Go template for values.yaml.
	// Placeholders like {{ .Param }} are filled by the wizard using ManifestParam values.
	ValuesTemplate string `protobuf:"bytes,5,opt,name=values_template,json=valuesTemplate,proto3" json:"values_template,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HelmChart) Reset() {
	*x = HelmChart{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmChart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmChart) ProtoMessage() {}

func (x *HelmChart) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmChart.ProtoReflect.Descriptor instead.
func (*HelmChart) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *HelmChart) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *HelmChart) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *HelmChart) GetChartName() string {
	if x != nil {
		return x.ChartName
	}
	return ""
}

func (x *HelmChart) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelmChart) GetValuesTemplate() string {
	if x != nil {
		return x.ValuesTemplate
	}
	return ""
}

// Dependency describes something the plugin needs to exist in the cluster.
// Each dependency is either already present (the operator points to it)
// or can be installed by the Cosmonaut wizard.
type Dependency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique identifier of this dependency.
	// Examples: "spark-operator", "trino", "polaris", "flink-operator"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// display_name is the human-readable name shown in the UI wizard.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// description explains what this dependency is and why it is needed.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// required indicates whether the plugin cannot function without this dependency.
	Required bool `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	// installable indicates whether Cosmonaut can install this dependency.
	// If false, the operator must provide it (e.g. a managed cloud service).
	Installable bool `protobuf:"varint,5,opt,name=installable,proto3" json:"installable,omitempty"`
	// chart is the Helm chart to install if installable=true and the operator
	// chooses to install rather than point to an existing instance.
	// Nil if installable=false.
	Chart         *HelmChart `protobuf:"bytes,6,opt,name=chart,proto3" json:"chart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *Dependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dependency) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Dependency) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Dependency) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Dependency) GetInstallable() bool {
	if x != nil {
		return x.Installable
	}
	return false
}

func (x *Dependency) GetChart() *HelmChart {
	if x != nil {
		return x.Chart
	}
	return nil
}

// ManifestParam is a parameter the wizard collects from the operator
// to fill in the component_template and values_template placeholders.
type ManifestParam struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the parameter identifier used in templates.
	// Example: "endpoint"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// display_name is the human-readable label shown in the UI.
	// Example: "Trino coordinator URL"
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// description explains what this parameter is for.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// default_value is used when the operator does not provide a value.
	DefaultValue string `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// required indicates whether the operator must provide this value.
	Required bool `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	// secret indicates whether this value should be stored in Vault/K8s Secret.
	// Example: passwords, tokens.
	Secret        bool `protobuf:"varint,6,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestParam) Reset() {
	*x = ManifestParam{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestParam) ProtoMessage() {}

func (x *ManifestParam) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestParam.ProtoReflect.Descriptor instead.
func (*ManifestParam) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *ManifestParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManifestParam) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ManifestParam) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ManifestParam) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ManifestParam) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ManifestParam) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

// PluginManifest describes everything needed to install and configure a plugin
// and its dependencies. Used by the Cosmonaut UI wizard and CLI installer.
type PluginManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// plugin_chart is the Helm chart for the plugin itself (e.g. cosmonaut-plugin-trino).
	PluginChart *HelmChart `protobuf:"bytes,1,opt,name=plugin_chart,json=pluginChart,proto3" json:"plugin_chart,omitempty"`
	// dependencies lists everything the plugin needs in the cluster.
	// The wizard guides the operator through each one.
	Dependencies []*Dependency `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	// component_template is a Go template for the CosmoComponent YAML.
	// Filled with ManifestParam values collected by the wizard.
	// Example:
	//
	//	apiVersion: cosmonaut.galileostd.io/v1
	//	kind: CosmoComponent
	//	spec:
	//	  endpoint: "http://{{ .endpoint }}:8080"
	ComponentTemplate string `protobuf:"bytes,3,opt,name=component_template,json=componentTemplate,proto3" json:"component_template,omitempty"`
	// params lists the parameters the wizard needs to collect from the operator.
	Params        []*ManifestParam `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *PluginManifest) GetPluginChart() *HelmChart {
	if x != nil {
		return x.PluginChart
	}
	return nil
}

func (x *PluginManifest) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *PluginManifest) GetComponentTemplate() string {
	if x != nil {
		return x.ComponentTemplate
	}
	return ""
}

func (x *PluginManifest) GetParams() []*ManifestParam {
	if x != nil {
		return x.Params
	}
	return nil
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{26}
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *PluginManifest        `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *GetManifestResponse) GetManifest() *PluginManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

var File_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x16plugin/v1/plugin.proto\x12\tplugin.v1\"\xce\x01\n" +
	"\tComponent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x128\n" +
	"\x06config\x18\x04 \x03(\v2 .plugin.v1.Component.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x11\n" +
	"\x0fDescribeRequest\"\x84\x03\n" +
	"\x10DescribeResponse\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x126\n" +
	"\vplugin_type\x18\x05 \x01(\x0e2\x15.plugin.v1.PluginTypeR\n" +
	"pluginType\x12?\n" +
	"\x0eexecution_type\x18\x06 \x01(\x0e2\x18.plugin.v1.ExecutionTypeR\rexecutionType\x12<\n" +
	"\rworkload_type\x18\a \x01(\x0e2\x17.plugin.v1.WorkloadTypeR\fworkloadType\x129\n" +
	"\fcapabilities\x18\b \x03(\v2\x15.plugin.v1.CapabilityR\fcapabilities\"H\n" +
	"\x12HealthCheckRequest\x122\n" +
	"\tcomponent\x18\x01 \x01(\v2\x14.plugin.v1.ComponentR\tcomponent\"\xe0\x01\n" +
	"\x13HealthCheckResponse\x12,\n" +
	"\x05state\x18\x01 \x01(\x0e2\x16.plugin.v1.HealthStateR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12E\n" +
	"\adetails\x18\x03 \x03(\v2+.plugin.v1.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x01\n" +
	"\x0eExecuteRequest\x122\n" +
	"\tcomponent\x18\x01 \x01(\v2\x14.plugin.v1.ComponentR\tcomponent\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12@\n" +
	"\apayload\x18\x03 \x03(\v2&.plugin.v1.ExecuteRequest.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x01\n" +
	"\x0fExecuteResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.plugin.v1.JobStateR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12>\n" +
	"\x06result\x18\x04 \x03(\v2&.plugin.v1.ExecuteResponse.ResultEntryR\x06result\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\rGetJobRequest\x122\n" +
	"\tcomponent\x18\x01 \x01(\v2\x14.plugin.v1.ComponentR\tcomponent\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"\xea\x01\n" +
	"\x0eGetJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.plugin.v1.JobStateR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12@\n" +
	"\adetails\x18\x04 \x03(\v2&.plugin.v1.GetJobResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x01\n" +
	"\x0fListJobsRequest\x122\n" +
	"\tcomponent\x18\x01 \x01(\v2\x14.plugin.v1.ComponentR\tcomponent\x126\n" +
	"\fstate_filter\x18\x02 \x01(\x0e2\x13.plugin.v1.JobStateR\vstateFilter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"W\n" +
	"\x10ListJobsResponse\x12-\n" +
	"\x04jobs\x18\x01 \x03(\v2\x19.plugin.v1.GetJobResponseR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"]\n" +
	"\x10CancelJobRequest\x122\n" +
	"\tcomponent\x18\x01 \x01(\v2\x14.plugin.v1.ComponentR\tcomponent\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"I\n" +
	"\x11CancelJobResponse\x12\x1a\n" +
	"\bcanceled\x18\x01 \x01(\bR\bcanceled\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x95\x01\n" +
	"\x0eGetLogsRequest\x122\n" +
	"\tcomponent\x18\x01 \x01(\v2\x14.plugin.v1.ComponentR\tcomponent\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x04 \x01(\x05R\ttailLines\"'\n" +
	"\x0fGetLogsResponse\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\"\x9d\x01\n" +
	"\x10SavepointRequest\x122\n" +
	"\tcomponent\x18\x01 \x01(\v2\x14.plugin.v1.ComponentR\tcomponent\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vtarget_path\x18\x03 \x01(\tR\n" +
	"targetPath\x12\x1d\n" +
	"\n" +
	"cancel_job\x18\x04 \x01(\bR\tcancelJob\"T\n" +
	"\x11SavepointResponse\x12%\n" +
	"\x0esavepoint_path\x18\x01 \x01(\tR\rsavepointPath\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe9\x01\n" +
	"\x0eRestoreRequest\x122\n" +
	"\tcomponent\x18\x01 \x01(\v2\x14.plugin.v1.ComponentR\tcomponent\x12%\n" +
	"\x0esavepoint_path\x18\x02 \x01(\tR\rsavepointPath\x12@\n" +
	"\apayload\x18\x03 \x03(\v2&.plugin.v1.RestoreRequest.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x0fRestoreResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.plugin.v1.JobStateR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"^\n" +
	"\x11GetMetricsRequest\x122\n" +
	"\tcomponent\x18\x01 \x01(\v2\x14.plugin.v1.ComponentR\tcomponent\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"\x96\x01\n" +
	"\x12GetMetricsResponse\x12D\n" +
	"\ametrics\x18\x01 \x03(\v2*.plugin.v1.GetMetricsResponse.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x01\n" +
	"\tHelmChart\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x1b\n" +
	"\trepo_name\x18\x02 \x01(\tR\brepoName\x12\x1d\n" +
	"\n" +
	"chart_name\x18\x03 \x01(\tR\tchartName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12'\n" +
	"\x0fvalues_template\x18\x05 \x01(\tR\x0evaluesTemplate\"\xcf\x01\n" +
	"\n" +
	"Dependency\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12 \n" +
	"\vinstallable\x18\x05 \x01(\bR\vinstallable\x12*\n" +
	"\x05chart\x18\x06 \x01(\v2\x14.plugin.v1.HelmChartR\x05chart\"\xc1\x01\n" +
	"\rManifestParam\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\bR\x06secret\"\xe5\x01\n" +
	"\x0ePluginManifest\x127\n" +
	"\fplugin_chart\x18\x01 \x01(\v2\x14.plugin.v1.HelmChartR\vpluginChart\x129\n" +
	"\fdependencies\x18\x02 \x03(\v2\x15.plugin.v1.DependencyR\fdependencies\x12-\n" +
	"\x12component_template\x18\x03 \x01(\tR\x11componentTemplate\x120\n" +
	"\x06params\x18\x04 \x03(\v2\x18.plugin.v1.ManifestParamR\x06params\"\x14\n" +
	"\x12GetManifestRequest\"L\n" +
	"\x13GetManifestResponse\x125\n" +
	"\bmanifest\x18\x01 \x01(\v2\x19.plugin.v1.PluginManifestR\bmanifest*\xc9\x02\n" +
	"\n" +
	"PluginType\x12\x1b\n" +
	"\x17PLUGIN_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PLUGIN_TYPE_QUERY_ENGINE\x10\x01\x12\x1a\n" +
	"\x16PLUGIN_TYPE_PROCESSING\x10\x02\x12\x1d\n" +
	"\x19PLUGIN_TYPE_ORCHESTRATION\x10\x03\x12\x17\n" +
	"\x13PLUGIN_TYPE_STORAGE\x10\x04\x12\x17\n" +
	"\x13PLUGIN_TYPE_CATALOG\x10\x05\x12\x19\n" +
	"\x15PLUGIN_TYPE_STREAMING\x10\x06\x12\x12\n" +
	"\x0ePLUGIN_TYPE_ML\x10\a\x12\x1d\n" +
	"\x19PLUGIN_TYPE_OBSERVABILITY\x10\b\x12\x18\n" +
	"\x14PLUGIN_TYPE_NOTEBOOK\x10\t\x12\x12\n" +
	"\x0ePLUGIN_TYPE_BI\x10\n" +
	"\x12\x17\n" +
	"\x13PLUGIN_TYPE_GENERIC\x10c*\x88\x01\n" +
	"\rExecutionType\x12\x1e\n" +
	"\x1aEXECUTION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EXECUTION_TYPE_WORKLOAD\x10\x01\x12\x18\n" +
	"\x14EXECUTION_TYPE_QUERY\x10\x02\x12 \n" +
	"\x1cEXECUTION_TYPE_OBSERVABILITY\x10\x03*c\n" +
	"\fWorkloadType\x12\x1d\n" +
	"\x19WORKLOAD_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13WORKLOAD_TYPE_BATCH\x10\x01\x12\x1b\n" +
	"\x17WORKLOAD_TYPE_STREAMING\x10\x02*\x96\x01\n" +
	"\vHealthState\x12\x1c\n" +
	"\x18HEALTH_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14HEALTH_STATE_HEALTHY\x10\x01\x12\x19\n" +
	"\x15HEALTH_STATE_DEGRADED\x10\x02\x12\x1a\n" +
	"\x16HEALTH_STATE_UNHEALTHY\x10\x03\x12\x18\n" +
	"\x14HEALTH_STATE_UNKNOWN\x10\x04*\xb1\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_PENDING\x10\x01\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x02\x12\x17\n" +
	"\x13JOB_STATE_SUCCEEDED\x10\x03\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x04\x12\x16\n" +
	"\x12JOB_STATE_CANCELED\x10\x05\x12\x15\n" +
	"\x11JOB_STATE_UNKNOWN\x10\x062\x95\x06\n" +
	"\rPluginService\x12C\n" +
	"\bDescribe\x12\x1a.plugin.v1.DescribeRequest\x1a\x1b.plugin.v1.DescribeResponse\x12L\n" +
	"\vHealthCheck\x12\x1d.plugin.v1.HealthCheckRequest\x1a\x1e.plugin.v1.HealthCheckResponse\x12@\n" +
	"\aExecute\x12\x19.plugin.v1.ExecuteRequest\x1a\x1a.plugin.v1.ExecuteResponse\x12=\n" +
	"\x06GetJob\x12\x18.plugin.v1.GetJobRequest\x1a\x19.plugin.v1.GetJobResponse\x12C\n" +
	"\bListJobs\x12\x1a.plugin.v1.ListJobsRequest\x1a\x1b.plugin.v1.ListJobsResponse\x12F\n" +
	"\tCancelJob\x12\x1b.plugin.v1.CancelJobRequest\x1a\x1c.plugin.v1.CancelJobResponse\x12@\n" +
	"\aGetLogs\x12\x19.plugin.v1.GetLogsRequest\x1a\x1a.plugin.v1.GetLogsResponse\x12F\n" +
	"\tSavepoint\x12\x1b.plugin.v1.SavepointRequest\x1a\x1c.plugin.v1.SavepointResponse\x12@\n" +
	"\aRestore\x12\x19.plugin.v1.RestoreRequest\x1a\x1a.plugin.v1.RestoreResponse\x12I\n" +
	"\n" +
	"GetMetrics\x12\x1c.plugin.v1.GetMetricsRequest\x1a\x1d.plugin.v1.GetMetricsResponse\x12L\n" +
	"\vGetManifest\x12\x1d.plugin.v1.GetManifestRequest\x1a\x1e.plugin.v1.GetManifestResponseB;Z9github.com/galileostd/cosmonaut-sdk/go/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_plugin_v1_plugin_proto_rawDescData []byte
)

func file_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_plugin_v1_plugin_proto_rawDescData
}

var file_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_plugin_v1_plugin_proto_goTypes = []any{
	(PluginType)(0),             // 0: plugin.v1.PluginType
	(ExecutionType)(0),          // 1: plugin.v1.ExecutionType
	(WorkloadType)(0),           // 2: plugin.v1.WorkloadType
	(HealthState)(0),            // 3: plugin.v1.HealthState
	(JobState)(0),               // 4: plugin.v1.JobState
	(*Component)(nil),           // 5: plugin.v1.Component
	(*Capability)(nil),          // 6: plugin.v1.Capability
	(*DescribeRequest)(nil),     // 7: plugin.v1.DescribeRequest
	(*DescribeResponse)(nil),    // 8: plugin.v1.DescribeResponse
	(*HealthCheckRequest)(nil),  // 9: plugin.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 10: plugin.v1.HealthCheckResponse
	(*ExecuteRequest)(nil),      // 11: plugin.v1.ExecuteRequest
	(*ExecuteResponse)(nil),     // 12: plugin.v1.ExecuteResponse
	(*GetJobRequest)(nil),       // 13: plugin.v1.GetJobRequest
	(*GetJobResponse)(nil),      // 14: plugin.v1.GetJobResponse
	(*ListJobsRequest)(nil),     // 15: plugin.v1.ListJobsRequest
	(*ListJobsResponse)(nil),    // 16: plugin.v1.ListJobsResponse
	(*CancelJobRequest)(nil),    // 17: plugin.v1.CancelJobRequest
	(*CancelJobResponse)(nil),   // 18: plugin.v1.CancelJobResponse
	(*GetLogsRequest)(nil),      // 19: plugin.v1.GetLogsRequest
	(*GetLogsResponse)(nil),     // 20: plugin.v1.GetLogsResponse
	(*SavepointRequest)(nil),    // 21: plugin.v1.SavepointRequest
	(*SavepointResponse)(nil),   // 22: plugin.v1.SavepointResponse
	(*RestoreRequest)(nil),      // 23: plugin.v1.RestoreRequest
	(*RestoreResponse)(nil),     // 24: plugin.v1.RestoreResponse
	(*GetMetricsRequest)(nil),   // 25: plugin.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),  // 26: plugin.v1.GetMetricsResponse
	(*HelmChart)(nil),           // 27: plugin.v1.HelmChart
	(*Dependency)(nil),          // 28: plugin.v1.Dependency
	(*ManifestParam)(nil),       // 29: plugin.v1.ManifestParam
	(*PluginManifest)(nil),      // 30: plugin.v1.PluginManifest
	(*GetManifestRequest)(nil),  // 31: plugin.v1.GetManifestRequest
	(*GetManifestResponse)(nil), // 32: plugin.v1.GetManifestResponse
	nil,                         // 33: plugin.v1.Component.ConfigEntry
	nil,                         // 34: plugin.v1.HealthCheckResponse.DetailsEntry
	nil,                         // 35: plugin.v1.ExecuteRequest.PayloadEntry
	nil,                         // 36: plugin.v1.ExecuteResponse.ResultEntry
	nil,                         // 37: plugin.v1.GetJobResponse.DetailsEntry
	nil,                         // 38: plugin.v1.RestoreRequest.PayloadEntry
	nil,                         // 39: plugin.v1.GetMetricsResponse.MetricsEntry
}
var file_plugin_v1_plugin_proto_depIdxs = []int32{
	33, // 0: plugin.v1.Component.config:type_name -> plugin.v1.Component.ConfigEntry
	0,  // 1: plugin.v1.DescribeResponse.plugin_type:type_name -> plugin.v1.PluginType
	1,  // 2: plugin.v1.DescribeResponse.execution_type:type_name -> plugin.v1.ExecutionType
	2,  // 3: plugin.v1.DescribeResponse.workload_type:type_name -> plugin.v1.WorkloadType
	6,  // 4: plugin.v1.DescribeResponse.capabilities:type_name -> plugin.v1.Capability
	5,  // 5: plugin.v1.HealthCheckRequest.component:type_name -> plugin.v1.Component
	3,  // 6: plugin.v1.HealthCheckResponse.state:type_name -> plugin.v1.HealthState
	34, // 7: plugin.v1.HealthCheckResponse.details:type_name -> plugin.v1.HealthCheckResponse.DetailsEntry
	5,  // 8: plugin.v1.ExecuteRequest.component:type_name -> plugin.v1.Component
	35, // 9: plugin.v1.ExecuteRequest.payload:type_name -> plugin.v1.ExecuteRequest.PayloadEntry
	4,  // 10: plugin.v1.ExecuteResponse.state:type_name -> plugin.v1.JobState
	36, // 11: plugin.v1.ExecuteResponse.result:type_name -> plugin.v1.ExecuteResponse.ResultEntry
	5,  // 12: plugin.v1.GetJobRequest.component:type_name -> plugin.v1.Component
	4,  // 13: plugin.v1.GetJobResponse.state:type_name -> plugin.v1.JobState
	37, // 14: plugin.v1.GetJobResponse.details:type_name -> plugin.v1.GetJobResponse.DetailsEntry
	5,  // 15: plugin.v1.ListJobsRequest.component:type_name -> plugin.v1.Component
	4,  // 16: plugin.v1.ListJobsRequest.state_filter:type_name -> plugin.v1.JobState
	14, // 17: plugin.v1.ListJobsResponse.jobs:type_name -> plugin.v1.GetJobResponse
	5,  // 18: plugin.v1.CancelJobRequest.component:type_name -> plugin.v1.Component
	5,  // 19: plugin.v1.GetLogsRequest.component:type_name -> plugin.v1.Component
	5,  // 20: plugin.v1.SavepointRequest.component:type_name -> plugin.v1.Component
	5,  // 21: plugin.v1.RestoreRequest.component:type_name -> plugin.v1.Component
	38, // 22: plugin.v1.RestoreRequest.payload:type_name -> plugin.v1.RestoreRequest.PayloadEntry
	4,  // 23: plugin.v1.RestoreResponse.state:type_name -> plugin.v1.JobState
	5,  // 24: plugin.v1.GetMetricsRequest.component:type_name -> plugin.v1.Component
	39, // 25: plugin.v1.GetMetricsResponse.metrics:type_name -> plugin.v1.GetMetricsResponse.MetricsEntry
	27, // 26: plugin.v1.Dependency.chart:type_name -> plugin.v1.HelmChart
	27, // 27: plugin.v1.PluginManifest.plugin_chart:type_name -> plugin.v1.HelmChart
	28, // 28: plugin.v1.PluginManifest.dependencies:type_name -> plugin.v1.Dependency
	29, // 29: plugin.v1.PluginManifest.params:type_name -> plugin.v1.ManifestParam
	30, // 30: plugin.v1.GetManifestResponse.manifest:type_name -> plugin.v1.PluginManifest
	7,  // 31: plugin.v1.PluginService.Describe:input_type -> plugin.v1.DescribeRequest
	9,  // 32: plugin.v1.PluginService.HealthCheck:input_type -> plugin.v1.HealthCheckRequest
	11, // 33: plugin.v1.PluginService.Execute:input_type -> plugin.v1.ExecuteRequest
	13, // 34: plugin.v1.PluginService.GetJob:input_type -> plugin.v1.GetJobRequest
	15, // 35: plugin.v1.PluginService.ListJobs:input_type -> plugin.v1.ListJobsRequest
	17, // 36: plugin.v1.PluginService.CancelJob:input_type -> plugin.v1.CancelJobRequest
	19, // 37: plugin.v1.PluginService.GetLogs:input_type -> plugin.v1.GetLogsRequest
	21, // 38: plugin.v1.PluginService.Savepoint:input_type -> plugin.v1.SavepointRequest
	23, // 39: plugin.v1.PluginService.Restore:input_type -> plugin.v1.RestoreRequest
	25, // 40: plugin.v1.PluginService.GetMetrics:input_type -> plugin.v1.GetMetricsRequest
	31, // 41: plugin.v1.PluginService.GetManifest:input_type -> plugin.v1.GetManifestRequest
	8,  // 42: plugin.v1.PluginService.Describe:output_type -> plugin.v1.DescribeResponse
	10, // 43: plugin.v1.PluginService.HealthCheck:output_type -> plugin.v1.HealthCheckResponse
	12, // 44: plugin.v1.PluginService.Execute:output_type -> plugin.v1.ExecuteResponse
	14, // 45: plugin.v1.PluginService.GetJob:output_type -> plugin.v1.GetJobResponse
	16, // 46: plugin.v1.PluginService.ListJobs:output_type -> plugin.v1.ListJobsResponse
	18, // 47: plugin.v1.PluginService.CancelJob:output_type -> plugin.v1.CancelJobResponse
	20, // 48: plugin.v1.PluginService.GetLogs:output_type -> plugin.v1.GetLogsResponse
	22, // 49: plugin.v1.PluginService.Savepoint:output_type -> plugin.v1.SavepointResponse
	24, // 50: plugin.v1.PluginService.Restore:output_type -> plugin.v1.RestoreResponse
	26, // 51: plugin.v1.PluginService.GetMetrics:output_type -> plugin.v1.GetMetricsResponse
	32, // 52: plugin.v1.PluginService.GetManifest:output_type -> plugin.v1.GetManifestResponse
	42, // [42:53] is the sub-list for method output_type
	31, // [31:42] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_plugin_v1_plugin_proto_init() }
func file_plugin_v1_plugin_proto_init() {
	if File_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_plugin_v1_plugin_proto = out.File
	file_plugin_v1_plugin_proto_goTypes = nil
	file_plugin_v1_plugin_proto_depIdxs = nil
}
