// Package server provides base helpers for implementing a Cosmonaut plugin in Go.
//
// Usage:
//
//	type MyPlugin struct {
//	    server.UnimplementedPlugin
//	}
//
//	func (p *MyPlugin) Describe(...) { ... }
//	func (p *MyPlugin) HealthCheck(...) { ... }
//	func (p *MyPlugin) Execute(...) { ... }
//
// Then in main():
//
//	srv := server.New(":50051", &MyPlugin{})
//	srv.Serve(ctx)
package server

import (
	"context"
	"fmt"
	"log/slog"
	"net"
	"os"
	"os/signal"
	"syscall"

	"google.golang.org/grpc"
	"google.golang.org/grpc/health"
	"google.golang.org/grpc/health/grpc_health_v1"
	"google.golang.org/grpc/reflection"

	pluginv1 "github.com/galileostd/cosmonaut-sdk/go/plugin/v1"
)

// Plugin is the interface every Cosmonaut plugin must implement.
// Generated by protoc — this is the gRPC server interface.
// Re-exported here for convenience so plugin authors only need to import this package.
type Plugin = pluginv1.PluginServiceServer

// UnimplementedPlugin embeds the protoc-generated unimplemented server.
// Embed this in your plugin struct to get default "unimplemented" responses
// for RPCs you haven't implemented yet.
type UnimplementedPlugin struct {
	pluginv1.UnimplementedPluginServiceServer
}

// Server wraps a gRPC server with lifecycle management.
type Server struct {
	addr   string
	plugin Plugin
	grpc   *grpc.Server
}

// New creates a new plugin server.
func New(addr string, plugin Plugin) *Server {
	grpcSrv := grpc.NewServer(
		grpc.ChainUnaryInterceptor(
			loggingInterceptor,
			recoveryInterceptor,
		),
	)

	// register the plugin service
	pluginv1.RegisterPluginServiceServer(grpcSrv, plugin)

	// standard gRPC health check protocol
	// the control-plane uses this to verify the plugin gRPC server is alive
	// before calling HealthCheck (which checks the underlying tool)
	healthSrv := health.NewServer()
	grpc_health_v1.RegisterHealthServer(grpcSrv, healthSrv)
	healthSrv.SetServingStatus("", grpc_health_v1.HealthCheckResponse_SERVING)

	// reflection allows grpcurl and other tools to introspect the service
	reflection.Register(grpcSrv)

	return &Server{
		addr:   addr,
		plugin: plugin,
		grpc:   grpcSrv,
	}
}

// Serve starts the gRPC server and blocks until the context is canceled
// or a termination signal is received.
func (s *Server) Serve(ctx context.Context) error {
	lis, err := net.Listen("tcp", s.addr)
	if err != nil {
		return fmt.Errorf("failed to listen on %s: %w", s.addr, err)
	}

	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)

	errCh := make(chan error, 1)
	go func() {
		slog.Info("plugin server listening", "addr", s.addr)
		if err := s.grpc.Serve(lis); err != nil {
			errCh <- err
		}
	}()

	select {
	case err := <-errCh:
		return fmt.Errorf("plugin server error: %w", err)
	case sig := <-sigCh:
		slog.Info("received signal, shutting down", "signal", sig)
	case <-ctx.Done():
		slog.Info("context canceled, shutting down")
	}

	s.grpc.GracefulStop()
	return nil
}

// ── interceptors ──────────────────────────────────────────────────────────────

func loggingInterceptor(
	ctx context.Context,
	req any,
	info *grpc.UnaryServerInfo,
	handler grpc.UnaryHandler,
) (any, error) {
	slog.Info("gRPC request", "method", info.FullMethod)
	resp, err := handler(ctx, req)
	if err != nil {
		slog.Error("gRPC error", "method", info.FullMethod, "err", err)
	}
	return resp, err
}

func recoveryInterceptor(
	ctx context.Context,
	req any,
	info *grpc.UnaryServerInfo,
	handler grpc.UnaryHandler,
) (resp any, err error) {
	defer func() {
		if r := recover(); r != nil {
			slog.Error("panic in gRPC handler", "method", info.FullMethod, "panic", r)
			err = fmt.Errorf("internal error: %v", r)
		}
	}()
	return handler(ctx, req)
}
